### ISSUE TITLE
error: ambiguous overload for ‘operator==’ 

### ISSUE THREAD

**Issue by NeilTruter** [eProsima/Fast-CDR#140] opened 2023-02-17 11:01 UTC
When specifying '-typeobject' for fastddsgen, and then compiling my project, receiving the error below.
Changing nothing else but just removing '-typeobject' my project compiles fine.

(Using latest version of fastDDS, compiling my project in QtCreator, problem is on Windows and Ubuntu)

/usr/local/include/fastcdr/Cdr.h:1381: error: ambiguous overload for ‘operator==’ (operand types are ‘uint8_t’ {aka ‘unsigned char’} and ‘eprosima::fastcdr::Cdr::Endianness’)
In file included from /home/user/Projects/Generic/Libs/Omnibus/generated/Alarm.cxx:31:
/usr/local/include/fastcdr/Cdr.h: In member function ‘eprosima::fastcdr::Cdr& eprosima::fastcdr::Cdr::serialize(const std::vector<T>&, eprosima::fastcdr::Cdr::Endianness)’:
/usr/local/include/fastcdr/Cdr.h:1381:53: error: ambiguous overload for ‘operator==’ (operand types are ‘uint8_t’ {aka ‘unsigned char’} and ‘eprosima::fastcdr::Cdr::Endianness’)
 1381 |         m_swapBytes = (m_swapBytes && (m_endianness == endianness)) || (!m_swapBytes && (m_endianness != endianness));
      |                                        ~~~~~~~~~~~~ ^~ ~~~~~~~~~~
      |                                        |               |
      |                                        |               eprosima::fastcdr::Cdr::Endianness
      |                                        uint8_t {aka unsigned char}

/usr/local/include/fastrtps/types/TypeObject.h:18: In file included from /usr/local/include/fastrtps/types/TypeObject.h:18,
In file included from /usr/local/include/fastrtps/types/TypeObject.h:18,
                 from /home/user/Projects/Generic/Libs/Omnibus/generated/AlarmTypeObject.h:26,
                 from /home/user/Projects/Generic/Libs/Omnibus/generated/Alarm.cxx:30:
/usr/local/include/fastrtps/types/TypesBase.h:251:1: note: candidate: ‘typename std::enable_if<(std::is_arithmetic<_Tp>::value || std::is_enum<_Tp>::value), bool>::type eprosima::fastrtps::types::operator==(T, const eprosima::fastrtps::types::ReturnCode_t&) [with T = eprosima::fastcdr::Cdr::Endianness; typename std::enable_if<(std::is_arithmetic<_Tp>::value || std::is_enum<_Tp>::value), bool>::type = bool]’ (reversed)
  251 | operator ==(
      | ^~~~~~~~

/home/user/Projects/Generic/Libs/Omnibus/generated/Alarm.cxx:31: In file included from /home/user/Projects/Generic/Libs/Omnibus/generated/Alarm.cxx:31:
In file included from /home/user/Projects/Generic/Libs/Omnibus/generated/Alarm.cxx:31:
/usr/local/include/fastcdr/Cdr.h:1381:53: note: candidate: ‘operator==(int, int)’ (built-in)
 1381 |         m_swapBytes = (m_swapBytes && (m_endianness == endianness)) || (!m_swapBytes && (m_endianness != endianness));
      |                                        ~~~~~~~~~~~~~^~~~~~~~~~~~~

**Comment by JLBuenoLopez-eProsima** [comment] 2023-10-02 05:36
This is a duplicate of eProsima/Fast-DDS-Gen#187.

**Closed by JLBuenoLopez-eProsima** 2023-10-02 05:36 UTC
Labels: duplicate
